apiVersion: v1
kind: Service
metadata:
  name: backend-car-svc
  labels:
    app: api
spec:
  selector:
    app: api

  ports:
    - port: 80
      targetPort: 80

  type: LoadBalancer
